chore: RandomFactsActivity converted to MVVM and optimization of vals…
leonardorpaixao/ChuckNorrisFacts pull request #5
Opened 2019-08-06 06:06 UTC by leonardorpaixao

### :pushpin: Referências: NA

### :cyclone: Mudanças

Foi criado um ViewModel para trazer um random Fact, assim, as requisições para API não são mais feitas na activity. Por sua vez, a acitivity observa um LiveData presente no viewModel, que é atualizado a partir da resposta da API.

### :art: Mudanças de UI: NA

### :memo: Como testar:
      Verificar que ao selecionar a opção **Random Fact > God Chuck Norris Inlight me!**, um fato aleatório é trazido com sucesso.

2019-08-06 19:50 UTC, jcaiqueoliveira commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +            ?.observeOn(AndroidSchedulers.mainThread())
pq esses campos são opcionais ?

2019-08-06 19:50 UTC, jcaiqueoliveira commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +    fun getRandomFact(){
se vc obtem o valor através de um livedata, pq expor a função getRandomFact?

2019-08-06 19:51 UTC, jcaiqueoliveira commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +            ?.observeOn(AndroidSchedulers.mainThread())
vc não precisa fazer o observerOn dado que vc ta devolvendo um resultado para o livedata que sempre entrega um resultado na main thread. Confirma isso por favor ?

2019-08-06 19:52 UTC, jcaiqueoliveira commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +            }, { e ->
Um Vm não deve acessar um contexto jamais. O lifeCycle de um Vm é maior que o de uma activity. Ou seja, se tu passa um context aqui ele pode ser nullo caso a act esteja num estado de onDestroy. Vale a leitura sobre ViewModel do Android

2019-08-06 19:53 UTC, jcaiqueoliveira requested changes
Deixei comentários

2019-08-06 22:18 UTC, leonardorpaixao commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +    fun getRandomFact(){
a função serve para solicitar a API um random fact por vez.

2019-08-06 22:18 UTC, leonardorpaixao commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +            ?.observeOn(AndroidSchedulers.mainThread())
Retirado com sucesso, não sei o porque disso.

2019-08-06 22:18 UTC, leonardorpaixao commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +            ?.observeOn(AndroidSchedulers.mainThread())
Quando tentei rodar sem **observeOn**, crashou:

_W/System.err: java.lang.IllegalStateException: Cannot invoke setValue on a background thread
W/System.err:     at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:443)_

2019-08-06 22:18 UTC, leonardorpaixao commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +            }, { e ->
Entendido.

2019-08-06 22:49 UTC, jcaiqueoliveira commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +    fun getRandomFact(){
> a função serve para solicitar a API um random fact por vez.

mas pq expor? vc pode simplesmente fazer isso no init do vm não ?

2019-08-06 22:50 UTC, jcaiqueoliveira commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/domain/model/ScreenState.kt
> +package com.estudos.leonardo.chucknorrisfacts.domain.model
nice

2019-08-07 01:24 UTC, leonardorpaixao commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +    fun getRandomFact(){
mas se eu fizer no init, como vou dar o poder de solicitar um novo fato?

2019-08-07 03:08 UTC, jcaiqueoliveira commented on app/src/main/java/com/estudos/leonardo/chucknorrisfacts/view/RandomFactsViewModel.kt
> +            ?.observeOn(AndroidSchedulers.mainThread())
> Quando tentei rodar sem **observeOn**, crashou:
> 
> _W/System.err: java.lang.IllegalStateException: Cannot invoke setValue on a background thread W/System.err: at androidx.lifecycle.LiveData.assertMainThread(LiveData.java:443)_

Deve ter alguma forma de fazer isso a partir da api do live data, o problema aqui é que adicionar obserOn AndroidMain atrapalha na escrita de testes unitários. Podemos seguir com isso por hora mas no teste mt provavelmente vc vai precisar da atenção a isso

2019-08-07 03:08 UTC, jcaiqueoliveira approved these changes

2019-08-19 01:59 UTC, merged